version: "3.3"
services:
    app:
        container_name: app
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        image: php_nginx
        working_dir: /var/www/html
        ports:
            - "2001:80"
        restart: "always"
        volumes:
            - ./docker/http.d:/etc/nginx/http.d
            - ./docker/php-fpm:/usr/local/etc/php-fpm.d/
            - ./:/var/www/html
        networks:
            - ClickBeard
networks:
    ClickBeard:
        driver: bridge
